### ISSUE TITLE
"R" and "B" values switch when using two strips (on two pins)

### ISSUE THREAD

**Issue by piethon1** [pololu/pololu-led-strip-arduino#10]
[I'm using the Pololu 1.2 LED library (PololuLedStrip.h)]

I have an Arduino Uno and am able to get the LED library to work with one LED strip.  I want to add a second, with both strips responding to the same color.  Using the example "LedStripColorTester", I simply added an extra definition and line to send to two strips.  However, when the RGB color I enter gets sent to my new, second strip, the RGB colors are reversed.

i.e. I will send "255,0,0!" and the first correctly lights up RED but the second lights up as if I sent "0,0,255!"

Here's the code:
```javascript
/* LedStripColorTester: Example Arduino sketch that lets you
 * type in a color on a PC and see it on the LED strip.
 */
 
#include <PololuLedStrip.h>

// Create an ledStrip object on pin 12.
PololuLedStrip<12> ledStrip;
PololuLedStrip<11> ledStrip2;  // THIS IS THE SECOND LED STRIP I ADDED

// Create a buffer for holding 60 colors.  Takes 180 bytes.
#define LED_COUNT 30
rgb_color colors[LED_COUNT];

void setup()
{
  // Start up the serial port, for communication with the PC.
  Serial.begin(115200);
  Serial.println("Ready to receive colors."); 
}

void loop()
{
  // If any digit is received, we will go into integer parsing mode
  // until all three calls to parseInt return an interger or time out.
  if (Serial.available())
  {
    char c = Serial.peek();
    if (!(c >= '0' && c <= '9'))
    {
      Serial.read(); // Discard non-digit character
    }
    else
    {
      // Read the color from the computer.
      rgb_color color;
      color.red = Serial.parseInt();
      color.green = Serial.parseInt();
      color.blue = Serial.parseInt();

      // Update the colors buffer.
      for(byte i = 0; i < LED_COUNT; i++)
      {
        colors[i] = color;
      }

      // Write to the LED strip.
      ledStrip.write(colors, LED_COUNT);
      ledStrip2.write(colors, LED_COUNT);  // THIS IS THE SECOND WRITE LINE, but for some 
                        // reason, it reverses the RGB numbers that ledStrip gets.

      Serial.print("Showing color: ");
      Serial.print(color.red);
      Serial.print(",");
      Serial.print(color.green);
      Serial.print(",");
      Serial.println(color.blue);
    }
  }
}
```

I hope that explains it, basically it works fine EXCEPT for the reversing of the RGB on the second strip.

Thanks so much for any ideas or help!

edit: I tried using the 'regular' Pololu library, but it doesn't seem to work - I found the 1.2 version does so am using that.

**Comment by DavidEGrayson** [comment]
Hello.  Your code looks fine to me, and I don't see how the library would switch red and blue for one of your strips when it doesn't do it for the other.  The most likely explanation is that your second strip is a different type of LED strip, and its red and blue channels are swapped.  You could try swapping the two LED strips and see if the problem follows the LED strip or stays on pin 11.  Where did you get your LED strips from?  All of the Pololu LED strips use GRB or RGB order.

Either way, this is unlikely to be an issue with the library, so I will close it.  You can still add comments to it though.
