### ISSUE TITLE
Inconsistent behavior

### ISSUE THREAD

**Issue by tkrpata** [pololu/pololu-led-strip-arduino#11]
I'm getting really inconsistent behavior from my LED strip. Using the LedStripColorTester example, it will occasionally work as expected (enter 255,0,0! and get all red) but often will do something completely unexpected (enter 255,0,0! and get three blue lights at the top and everything else off). Because this is intermittent, I'm thinking it may somehow be related to my hardware or configuration somehow, but I thought I'd raise the issue here and see if anyone else is seeing similar behavior.

**Comment by kevin-pololu** [comment]
Hello.
If you're still having trouble with this, please use our regular support channels by posting on the [Pololu Forum](http://forum.pololu.com/) or [contacting us directly](https://www.pololu.com/contact). (Github issues are more appropriate for tracking library development and reporting bugs.)

If you contact us, it would be helpful for you to provide details on what you're using to power and control the LED strip, as well as a picture of your setup if possible.
