### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by bonnmailin** [pololu/pololu-led-strip-arduino#12]
Hi...there are some errors in pololu-led-strip-arduino while compiling.Any updated library or am I missing some part?

**Comment by DavidEGrayson** [comment]
This repository contains the latest version of the library.  You should double and triple check that you followed the installation instructions in the README.

**Comment by DavidEGrayson** [comment]
If you continue to have trouble, please give a detailed description of your setup and all the steps you took to reproduce the error, and include the full output from the compiler.

**Comment by bonnmailin** [comment]
Hi David, problem solved. I copied the last folder of PoloLEDStrip and take it out after library as below:
 
libraries>PololuLedStrip.

Thanks for your fast reply and concerned.
