### ISSUE TITLE
Not listed in the Arduino Library Manager

### ISSUE THREAD

**Issue by kmckee** [pololu/pololu-led-strip-arduino#14]
I can't seem to find this library in the Arduino Library Manager.  Could this be related to #13 ?

**Comment by DavidEGrayson** [comment]
Thanks for letting us know.  We are working on getting it added: https://github.com/arduino/Arduino/issues/5843

**Comment by ryantm** [comment]
It has been added. Thank you for letting us know it wasn't there!

Ryan
