### ISSUE TITLE
segments or pins

### ISSUE THREAD

**Issue by vavik96** [pololu/pololu-led-strip-arduino#15]
Hello, is it possible to use two or more string of LEDs  at once by dividing into segments  or connecting to different pins. 
Best regards

**Comment by kevin-pololu** [comment]
Yes, you have two options for controlling multiple groups of LEDs from one Arduino: you can either chain them together and control them as one long strip, or you can control them separately with a different pin and instance of the PololuLedStrip class for each.

If you have more questions, please post on the [Pololu forum](https://forum.pololu.com/), as the GitHub issues are intended for keeping track of problems with and changes to the library itself.

Kevin
