### ISSUE TITLE
Does not compile on MegaAVR boards.

### ISSUE THREAD

**Issue by westonmiller** [pololu/pololu-led-strip-arduino#17]
It does not compile on a Uno Wifi Rev2 board, the error leads me to believe it won't work on any MegaAVR boards.

Error Message
```
WARNING: library PololuLedStrip claims to run on avr, sam architecture(s) and may be incompatible with your current board which runs on megaavr architecture(s).
/Users/someguy/Documents/Arduino/libraries/PololuLedStrip/PololuLedStrip.h: In member function 'write':
/Users/someguy/Documents/Arduino/libraries/PololuLedStrip/PololuLedStrip.h:359:8: error: impossible constraint in 'asm'
       );
        ^
lto-wrapper: fatal error: /Users/someguy/Library/Arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino5/bin/avr-gcc returned 1 exit status
compilation terminated.
/Users/someguy/Library/Arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino5/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
exit status 1
```

**Comment by DavidEGrayson** [comment]
Hello.  This library only works with the boards listed in the ["Supported platforms" section of the README](https://github.com/pololu/pololu-led-strip-arduino#supported-platforms).  The library supports many megaAVR microcontrollers, but not the ATmega4809.  We think that the "megaavr" architecture in the Arduino IDE really just refers to the ATmega4809 at the moment, and that is why the error message is confusing.
