### ISSUE TITLE
Can you drive multiple stripes using one arduino?

### ISSUE THREAD

**Issue by ghost** [pololu/pololu-led-strip-arduino#18]
I’m thinking of having two strips of pixels that are individually driven using two separate pins. Is this possible without using two arduinos?

**Comment by DavidEGrayson** [comment]
Yes, you can make two different objects with different names that are on different pins.  You would probably want separate color buffers for them as well.  

We use GitHub issues to keep track of bugs and features requests in the library.  If you need more help getting your project working I suggest posting your questions and all the relevant details on the [Pololu forum](https://forum.pololu.com/).

**Comment by ghost** [comment]
I apologise for using the wrong platform, but thank you for your help.
