### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by MuneshThakur** [pololu/pololu-led-strip-arduino#9]
Hello Everyone
                          I have a new Addressable Pololu RGB Leds Strip and changing the color of this Strip using Arduino uno. But now I want to color change and On/Off the this Strip using Android Tablet via Button  and all these are think are connected via Arduino uno communicator(USB Cable) .So i need your help
Thanks & Regard 
Munesh parmar

**Comment by DavidEGrayson** [comment]
Hello, Munesh.

This is the issue tracker for the pololu-led-strip-arduino library, which is used to keep track of bugs or  feature requests for the library, so it is not an appropriate place for this type of question.  You might try posting in [our forum](http://forum.pololu.com/) instead.
